CodeCat/Models/ViewModeles/DocumentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CodeCat.Models;

namespace CodeCat.Models.ViewModeles
{
    public class DocumentViewModel
    {
        public DocumendModel document;   
    }
}

CodeCat/Models/ViewModels/DocumentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CodeCat.Models;

namespace CodeCat.Models.ViewModels
{
    public class DocumentViewModel
    {
        public DocumentModel document;

        public int? selectedDocument { get; set; }

        public List<DocumentModel> documents { get; set; }

        public string documentName { get; set; }

        public string docProjectName { get; set; }
    }
}

CodeCat/Controllers/DocumentController.cs
using CodeCat.Models;
using CodeCat.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CodeCat.Models.ViewModels;
using System.Web.Services;

namespace CodeCat.Controllers
{
    public class DocumentController : Controller
    {
        DocumentService docService = new DocumentService(null);

        // GET: Document
        public ActionResult Index()
        {
            return View();
        }

        [WebMethod]
        public string save(DocumentModel DocumentModel)
        {
            try
            {
                docService.saveDocument(DocumentModel.ID, DocumentModel.content);
                DocumentModel check = docService.getDocumentByID(DocumentModel.ID);

                if(DocumentModel.content == check.content)
                {
                    return "success";
                }

                return "error";
            }
            catch
            {
                return "error";
            }
        }

        [HttpGet]
        public ActionResult addDocument(FormCollection collection)
        {
            return View();
        }

        [HttpPost]
        public ActionResult addDocument(DocumentModel docFromUser)
        {
            if(ModelState.IsValid)
            {
                //Get the projectID from the url
                var url = Url.RequestContext.RouteData.Values["id"].ToString();
                int urlInt = int.Parse(url);

                //Create the new doc
                DocumentModel doc = new DocumentModel();
                doc = docFromUser;
                doc.name = docFromUser.name + "." + docFromUser.type.ToString();
                doc.content = "//Code::Cat";
                doc.projectID = urlInt;
                bool success = docService.addDocument(doc);

                if(success == true)
                {
                    return RedirectToAction("../Project/ShowDocument/" + doc.ID);
                }
                else
                {
                    ModelState.AddModelError("name", "Oops, this project already has a document with this name!");

                    return View(docFromUser);
                }
            }

            return RedirectToAction("../Home/Error");
        }
    }
}

CodeCat/Views/Document/AddDocument.cshtml
@model CodeCat.Models.DocumentModel
@{
    ViewBag.Title = "AddDocument";
}

<h2>Add Document</h2>

<!--LOGO-->
<div class="sign-in-logo-div">
    <img src="~/Images/kisi4.png" width="170" height="200" alt="Code Cat Logo" class="sign-up-logo" />
</div>
<hr />

@using (Html.BeginForm("addDocument", "Document", FormMethod.Post, new { @class = "add-document-form" }))
{
    @Html.AntiForgeryToken()
    <div class="add-document-div">
        <div class="form-group">
            @Html.LabelFor(m => m.type, new { @class = "control-label label-for-type-dropdown" })
            @Html.EnumDropDownListFor(m => m.type, new { @class = "form-control" })    
            @Html.ValidationMessageFor(m => m.type, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.name, new { @class = "control-label label-for-type-dropdown" })
            @Html.TextBoxFor(m => m.name, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.name, "", new { @class = "text-danger" })
        </div>

        <button type="submit" value="Create" id="create-button" onclick="createFeedback()" class="btn btn-fab">Create document</button>

        <script>
                function createFeedback() {
                    var name = $(".form-control").val();
                    toastr.success(name + " was added to your projects!");
                };
        </script>
    </div>
}